"""
base_aide.py — Cas de dépannage résolus, fournis par le service.

Fichier produit à partir du document d'aide : ne pas modifier à la
main, régénérer depuis la source si elle évolue.

Chaque entrée : (symptôme, gamme concernée, cause et solution).
"""

CAS = [
    ('Nombre de cycle d’une batterie OK', '',
     'Entre 500 & 1000 – 3000 pour les cybertank.'),
    ('INFOS A SAVOIRCONCERNANT LE RESEAU RTKANTENNE HORS COUVERTURE', 'rtk1',
     'Maintenant TOUT les robots RTK fonctionne en automatique lors de la recherche du signal rtk. Etre en FW 1.3.26 pour rtk1.m Les robots qui fonctionnait sur le reseau kress et qui on perdu le signal a cause d\'une antenne qui a disparu, il faut effacer la carte existante,désapparierle robot et refaire une installation "sortie de carton" SI ça ne marche pas ! le cas de robot qu\'ils faut commuter en reseaux étendu, il faut:mettre le robot en ligne, effacer toute les cartes, puis dans le backend , allez a "configuration" et derniere ligne "reprovision" , puis desapairer le compte pour que la tete se connecte au 1er reseau trouver« N’arrive pas à télécharger le firmware depuis KDP »= Firmware disponible sur backend, savoir si besoin du bootloader (pour les modèles 2022-2023) s\'il n\'y a pas de logo USB barrésur le cartondu robot.'),
    ('Demande d’avoir/inventaire', '',
     'Transférer aux ADV > FRB2BKress Orderdesk Inbound.'),
    ('Problème de facture', '',
     'Switch ADV'),
    ('Erreur de connexion', '',
     'lorsque le client veut se connecter au robot »= Voir sur backend si l’adresse mail n’est pas celle du revendeur mais du client.'),
    ('Problèmes batterie KR122E (l’appareil se décharge alors qu’il est éteint et non utilisé)', '',
     'Le clavier est en court-circuit, à remplacer.'),
    ("Le robot ne s'allume plus après test de réveil de batterie", '',
     'Batterie HS, à remplacer.'),
    ('Le robot ne s’allume pas', '',
     'Cause : Batterie ; Bouton ON /OFF ; Carte Mère.Solution : Vérifier la tension de la batterie ; Vérifier le fusible ; Vérifier le bouton ON/OFF.'),
    ('L’écran n’affiche plus rien', 'rtk1',
     'Circuit imprimé d’affichage HS.'),
    ('Le robot tourne autour d’un îlot sans ressortir', 'rtk1',
     'Cause : Deux îlots sont séparés de moins d’1 mètre ; Un îlot est à moins d’un mètre de la bordure.Solution : Inclure les deux îlots ensemble ; Inclure l’îlot à la bordure ; Supprimer l’îlot si l’OAS et/ou le parechoc seulement peut faire le travail.'),
    ('Le robot tond uniquement les bordures', '',
     'Cause : Robot lancé en mode bordure, fera le tour de toutes les zones puis de tous les îlots ; Robot ou tête non activé (RTK).Solution : Attendre la fin du cycle ou renvoyer le robot à la station puis l’éteindre et le rallumer ; Vérifier dans le backend si le robot a bien reçu les « jetons d’activation », sinon activez si nécessaire et renvoyez les jetons.'),
    ('Le robot annonce erreur de camera', 'rtk2',
     'Effectuer maj +Nettoyer la caméra ; débrancher / rebrancher le connecteur sinon le remplacer.'),
    ("Robot tond la bordure, ne tond pas l'intérieur de la zone mais tond les autres zones ou ne part pas travailler dans la zone et retourne à la station", '',
     'Cause : Etranglement de zone (passage <1m). Solution : Redessiner la zone.'),
    ('Robot ne finit pas ses bandes', 'rtk1',
     '\u200b= Cause : Détection OAS ; Erreurs soulèvement ; Déclenchement du pare chocs. Solution : Obstacle physique ou herbes hautes ; Roues avant HS ; Chocs par obstacle ou relief du terrain.'),
    ('Par quelle application je dois effectuer le nouveau mapping', '',
     'Solution : Le nouveau mapping s’effectue par l’application Kress Fleet.'),
    ('Robot toujours en démo suite au jeton d’activation', '',
     'Cause : Le robot n’a pas été activé dans le KDP. Solution : Activé le robot dans le KDP puis télécharger le nouveau jeton d’activation. Une image contenant texte, capture d’écran, Police, nombre Le contenu généré par l’IA peut être incorrect.Une image contenant texte, capture d’écran, Police, ligne Le contenu généré par l’IA peut être incorrect.'),
    ('Robot – problèmelame/hauteur de coupe', 'rtk1',
     "Problème : Echec installation de la lame ; Blocage de la hauteur de coupe ; La page n’apparaît plus dans le menu de diag ; Réglage de lahauteur de coupe.Cause :Capteur de bande magnétique (peutcourt-circuiteret ne plus envoyer les infos) ; Carte imprimé du moteur de coupe ; Vérifier si l’aimant estprésentau niveaudu moteur de coupe/tonte ; Module magnétique ; Moteur de coupe.Solution : Effectuer le remplacement de ceux-ci. Erreur 2Erreur3 KR236RTK1 TEST :ilrègleen 1er 60, puis 30, puis 45 normalementçarecalibre le moteurdans DIAG Letruc gris doit être vu de l’extérieur (aimant)l'erreur 3 souvent, si tout semble bon physiquement/mécaniquement c'est possible que ce soit les faisceaux ou les capteurs"),
    ('Pour les robots filaires, il faut utiliser l’application Mission', 'filaire',
     '.Robot filaire'),
    ('Installation d’un robot filaire', 'filaire',
     'Problème : Robot qui s’arrête en plein milieu du terrain. Cause : Valeur d’installation beaucoup trop haute d’après les préconisations de POSITEC. Solution : Aller dans le log de la tondeuse ; chercher « Boundary length », si la hauteur dépasse 350M il faut changer l’installation ou faire un échange.Les préconisations ont étaient donné en été 2024 ; haut-delà c’est au revendeur de prendre sa responsabilité dessus.'),
    ('Client qui appel pour réinitialiser le périmètre sur un robot filaire', 'filaire',
     'Solution :Il doit réduire le fil.'),
    ('Robot ne sort pas de sa station de charge, départ OK similaire', '',
     'Problème : Départ charge échoué.Cause :Station de charge n’arrive pas à rejoindre la zone.Solution : Remapper le chemin de retour station de charge.'),
    ('Supprimer un robot de son APP CLIENT', '',
     'Solution : KRESS RKT > Montondeuses > Retirer la tondeuse souhaitée.'),
    ('Robot qui fait du hors limite– pivote sur lui-même–est totalement perdu', 'rtk1',
     'Problème : Odomètre mal branché – aimant manquant. Cause :Voir dans le fichier LOG : CTRL+F > Fusion M > Valeur de gauche et de droite doivent avoir des nombres autre que 0 Solution : Vérifier dans la roue si l’odomètre est correctement branché au niveau du connecteur – voir si l’aimant esten place'),
    ("Un robot qui fait que rentrer à la base dès qu'il active son mode tonte(RTK2)", 'rtk2',
     'Solution :désactivation du mode bordure.sur fleet>tondeuses>play on peut sélectionner le curseur activer les bordures'),
    ('Robot bloque sur l’affichage KRESS–MAJ impossible', 'rtk1',
     'Problème :Tête qui plantesi remplacement carte mère ne fait rien.Cause : Aléatoire électronique.Solution :Débrancher le modulemagnétiqueàréinitialiser la têtevia backend +maj bootloader > Si ça ne fonctionne pas, remplacement de la tête.'),
    ('N’arrive pas à rentrerle code PIN', 'rtk1',
     'Problème :Circuit Board ou lemicro-switchsont en échec. Solution :Si après remplacementça ne fonctionne pas > Batterie en cause.'),
    ('Robot ayant un problème de suivit de filet moteur de lame', '',
     'Problème :Il ne suit pas le fil et le moteur de lame ne s’arrête pas.Cause : Aléatoire électrique. Solution : Remplacement de la carte principal+ carte écran + faisceau complet + détecteur droit et gauche de fil.'),
    ('Robot coincé', '',
     'Problème : Affiche le message robot coincé en permanence. Cause :Il peut manquer l’aimant des roues Solution :Vérifier si l’aimant est présent,capteur de choccollision.'),
    ('Robot ne rentre pas à sa base (station de charge)', 'rtk1',
     'Problème : Il ne rentre pas à sa station de rechargeet passait devant sans déclencher la charge et s’arrêter.Cause :Ça peut venir de l’aimant ou de la tête de la station de recharge. Solution :Si présence de l’aimant > Essayer une autre tête.'),
    ('Robot ne rentre pas à sa base (station de charge)', 'rtk1',
     'Problème : Il ne rentre pas à sa station de recharge, tentative de mise à jour mais ne fonctionne pas, remappage de la station, déplacement de la station.Cause :L’aimant peut être abiméou HS Solution :Remplacement de l’aimant.'),
    ('Robot affiche défaut de fil manquant', 'filaire',
     'Problème : Il affichedéfaut de fil manquant.Solution : Remplacer le capteur de signalfil ; le transformateuret la carte de la station.'),
    ('Voyant de base ne s’allume pas', '',
     'Problème : Le voyant de la base ne s’allume pas mais le chargeur et la base de charge fonctionnent. Solution : Câble d’alimentation.'),
    ('Robot tourne en rond sur la bande magnétique', 'rtk1',
     'Solution : Remplacement de la carte de bande magnétique.'),
    ('Impossiblede se connecter au Serveur NTRIP', '',
     "Problème :NTRIP : Un client est en train d'installer son robot KR283 et il a un message d'erreur.Solution :Il faut patienter quelques minutes que le robot se connecte au réseau RTK avant de lancer le mapping."),
    ('Robot qui affiche Visual Feature Augmentation', 'rtk2',
     "Problème :Sûrement lié au mapping via l’application.Solution :On cartographie le terrain avec le chariot rtk2, puis on la publie. Ensuite on fait une nouvelle carte avec le téléphone d'environ 5 m2. Puis on fait tondre le robot dans cette petite zone. Puis on désactive cette carte et on active la 1ère. Etlà,normalement, le robot fonctionne."),
    ('Robot affiche un message d’erreur à la place du Code OTP lors du scan du QRCODE', 'rtk1',
     "Problème : Applink en cours d'exécution, utiliser l'appli pour se connecter. Solution : Eteindre le robot puis le rallumer ; de même pour l’application."),
    ('Robotconsomme de la batterie', '',
     'Problème :Le robot consomme de la batterieen étant éteint–consommation de plus de 50% en une nuit. Solution :Batterie pour test – Si non OK changement de la carte écran.'),
    ('Robotbloqué mode démo', '',
     'Solution :Fichier Unlockou configwith head.'),
    ('Robot modifier la limite d’une zone', 'rtk2',
     "Problème :Un client veut modifier la limite d'une zone c'est obligatoirement avec un cart ?Non !Il veut faire avec le robot même mais ça ne le propose pas KR281E.Solution :Trop d'appareil dans son téléphonele robot n’était pasen Bluetoothetil n’était passur KRESS RTKpourla modification.Sinon effacer le robot de son Bluetooth sur le téléphone et recommencerl’appairage."),
    ('Applicationvalidation compte client fleet sur rtkn', '',
     'Problème :N\'arrivait pas à valider "passer à kress rtkn" sur le compte client fleet : Résolution :Il avaitmisle chariot sur le compte client fleet du coup onnepouvait pas continuer, il fallait enlever le chariot du compte client afin de continuer l\'étape suivant.'),
    ('Freeproblèmede connexion', '',
     'Solution :Ils doivent s’assurer d’être en 2.4ghz et siça ne marche toujours pasils doivent créer un réseau invité et mettre un mot de passe ultra simpleexemple : Kress2025 Installer l’applicationfreebox connect>Aller surla box du client Demander le mdp outenter« password »pourle mot depasse pardéfaut Créer un réseauinvitépuis connecter lerobot au réseau invité.« Pas de carte. head demo, body demo »= Solution :Appairer la4Gou Unpairle head et refairel’appairage.'),
    ('Chargeur qui met 4h à chargersur KR174E', 'rtk1',
     "Solution:Changer le transformateur : bloc de charge et l'alimentation > KR174E."),
    ('Stationde chargeen vert et bleu mais wificapte bien', '',
     'Solution :Appuyer 10 secondes bouton reset sur la station de charge. Puis appuyer 4 secondes sur le robotcela fait un resetpourla station de charge.'),
    ('Robot s’arrête enplein terrain', '',
     "Solution :il faut qu'il regarde surtout si la diode 4G sur latêteclignote ou si elle est fixe. Sielle clignote, c'est bien unproblèmederéseau4G."),
    ('Erreur E32 sur RTK 2', 'rtk2',
     "Le code E32 indique qu'une zone n'est pas reliée par un guide. La tondeuse ne peut ni accéder à cette zone ni en revenir."),
    ('Erreur E107', 'rtk2',
     'Problème :Ce problème est dû au fait que la résolution de la carte de cartographie diffère de celle de la tondeuse : celle de la tondeuse est de 5 cm, tandis que celle de la carte est de 2 cm. Solution :Lasolutiontemporaire est d’utiliser la tondeuse pour recalibrer la carte. La solution à long terme sera mise en place vers le 20 avril.'),
    ('Erreur lors du départ de la station de charge', 'rtk1',
     'Problème :Fréquence durobot différentsdes plannings ; Problème destation. Solution :Vérifier lafréquence sur FLEET, dansles réglages généraux etcompareravec ceuxdes plannings ; Verrouillage du nez de base qui saute et du coup le nez de charge se met en travers. FILAIRE ENLEVER MODE DEMO= Menu diagnostic dernière page , flèche du bas > page service MDP = ABCDABCD'),
    ('Tondeuse à l’extérieur des limites', 'rtk1',
     'Problème :Le robot est en dehors de sa carte. Solution :Il faut déplacer le robot à l’intérieur de la carte.'),
    ('Tondeuse affiche : erreur de lame, lame bloqué', 'rtk1',
     'Problème :Le robot affiche sur FLEET le problème de lame bloqué. Solution :Essayer de remplacer lebloc dumoteur de coupe ; Le capteurde hauteur de lame ; L’assemblage du moteurdu réglage de la hauteur de lame ; La carte mère ; Câble du moteur de coupe ; Maj firmware.'),
    ('Tondeusese fige au milieu du terrain et s’éteint', 'rtk1',
     'Problème : Le robot commence à tondre puis va s’arrêter complètement au milieu du terrain et s’éteindre aussi net. Solution : Vérifier la version du firmware ; Vérifier dans le menu diagàtest moteuràtempérature des moteurs ; Test des capteurs ; Test de la batterie sur la page n°3 ; Vérifier le faisceau d’alimentation ; Remplacement de la carte mère ; Remplacement de l’antenne du robot.'),
    ("N'arrive pas à faire les mises à jour sur le robotmême si clé usb reconnu", '',
     'Solution: Débrancher la batterie et remettrepuis il va lire la clé usb.'),
    ('Erreurmoteur dedirection', '',
     'Problème :Le moteur estmort. Solution :Changer lemoteur.'),
    ('Problème de connexion au WIFI', '',
     'Problème : Le revendeur à configuré son installation WIFI à l’atelier et une fois arrivé chez le client, en configurant le réseau WIFI ça ne fonctionne pas.Solution : Reset de la station ou désapparier et refaire une installation.'),
    ('Lesultrasonsne fonctionnentplus correctement', '',
     'Problème :Les ultrasonsfonctionnent une foissur deux. Solution :Çapeut-êtreune erreur desertissageau niveaudu faisceau sinon remplacer faisceau ou capteurs.'),
    ('Robotaffiche ‘Map overlimit’', '',
     'Problème :La zoned’aircomplète dépasseles préconisations constructrices. Solution :Il fautque le client supprimeou réduitune zonepourrentrer dansl’air totalsupportéou qu’ilcréer une secondecarte avecles zones supprimées.'),
    ('Kress FAST2BASEKA0215.', '',
     'Problème:Combien il faut laisser en longueur de bandes magnétique en parallèle au fil périmétrique ; et pour le renvoi à 90°, combien il doit laisser de bandes ensuite. Solution:Ilfautlaisser deux bandes de 27cm espacé de 27cm.'),
    ('Robot déclaré en usage professionnel.', '',
     'Problème : Les robotsne sont plus pris sous garantie.Solution :Les robots déclaré en usage professionnel sont garantis 1AN. Il faudrait joindre une facture de venteclient.'),
    ('Bouton POWERqui ne fonctionne plus', '',
     'Problème :Le bouton POWERfonctionne parintermittence. Solution :Il fautvérifierque le bouton soit monté du bon sens.'),
    ('Robot affichel’erreur ‘évite unpiège’', '',
     "Problème :Le robot affiche cetteerreur, impossiblededémarreret d’aller tondre. Solution :Essayeren désactivant les capteurs ultras-sons ; Voirsi l’espaceestrestreint entre 2bordures(moins d'un mètre) ; Leparechoc/capteurdéfaillant,Laroues avant/capteur défaillant,Lemoteur de coupe bloqué. Head update failed soit le FW conporte une parenthese avec un chiffre à la fin du .pfb soit il refait une maj avec la version 1.3.24"),
    ('Erreur E18&Problèmeavec le moteur dela roueprincipale.', 'rtk2',
     'Problème :L’erreur E18 etl’erreurdu moteurde la roueprincipale s’afficheconstamment. Solution : 🔍Vérification 1 : Contrôler si les bornes du connecteur Hall sont anormales Étape 1 :Ouvrir le capot supérieur.Étape 2 :Retirer la structure de fixation ainsi que le faisceau de câbles de la carte de commande avant défectueuse.Étape 3 :Retirer le faisceau Hall.Étape 4 :Vérifier le bon maintien des bornes du connecteur ainsi que du faisceau de câbles. 🔍Vérification 2 : Contrôler si la carte de commande avant est défectueuse Étape 1 :Inverser les positions des cartes de commande avant gauche et droite.Étape 2 :Connecter le faisceau de câbles à la carte de commande avant.Étape 3 :Connecter le faisceau RTK et remettre le capot supérieur.Étape 4 :Mettre la tondeuse sous tension et effectuer le déplacement en contrôle Bluetooth via l’application mobile.Si l’erreur E18 apparaît toujours, merci de cop'),
]
